#!/bin/bash

#solution to question 4
#goal is to list the cities in Florida that have airports in the dataset

grep FL.*FL.*FL.*FL /ufrc/bsc4452/share/Class_Files/data/flights.May2017-Apr2018.csv | cut -f 3,4,5 -d "," | sort -u

#solution
"EYW","Key West, FL"
"FLL","Fort Lauderdale, FL"
"GNV","Gainesville, FL"
"JAX","Jacksonville, FL"
"MCO","Orlando, FL"
"MIA","Miami, FL"
"PNS","Pensacola, FL"
"RSW","Fort Myers, FL"
"TLH","Tallahassee, FL"
"TPA","Tampa, FL"
